/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'ownerName' : string,
  'instagram' : string,
  'whatsapp' : string,
  'email' : string,
  'facebook' : string,
  'phone' : string,
  'branches' : Array<string>,
}
export interface Course {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : CourseCategory,
}
export type CourseCategory = { 'Engineering' : null } |
  { 'Pharmacy' : null } |
  { 'EntranceExam' : null } |
  { 'Intermediate' : null };
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface HomePageContent {
  'missionStatement' : string,
  'contactText' : string,
  'heroSubtitle' : string,
  'aboutText' : string,
  'testimonialsHeading' : string,
  'heroTitle' : string,
}
export interface InternationalInquiry {
  'country' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ReviewImage {
  'id' : string,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface SubmittedReview {
  'id' : string,
  'content' : string,
  'name' : [] | [string],
  'rating' : bigint,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCourse' : ActorMethod<
    [string, string, CourseCategory, string],
    undefined
  >,
  'addOrUpdateGalleryImage' : ActorMethod<
    [string, ExternalBlob, string],
    undefined
  >,
  'addReviewImage' : ActorMethod<[string, ExternalBlob, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'getAllSubmittedReviews' : ActorMethod<[], Array<SubmittedReview>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getFeaturedGalleryImageIDs' : ActorMethod<[], Array<string>>,
  'getFeaturedGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHomePageContent' : ActorMethod<[boolean], HomePageContent>,
  'getInternationalInquiries' : ActorMethod<[], Array<InternationalInquiry>>,
  'getReviewImages' : ActorMethod<[], Array<ReviewImage>>,
  'getSubmittedReviews' : ActorMethod<[], Array<SubmittedReview>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishHomePageContent' : ActorMethod<[], undefined>,
  'removeCourse' : ActorMethod<[string], undefined>,
  'removeGalleryImage' : ActorMethod<[string], undefined>,
  'removeReviewImage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setFeaturedGalleryImageIDs' : ActorMethod<[Array<string>], undefined>,
  'submitInternationalInquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitReview' : ActorMethod<
    [string, [] | [string], string, bigint],
    undefined
  >,
  'updateContactInfo' : ActorMethod<
    [string, string, Array<string>, string, string, string, string],
    undefined
  >,
  'updateHomePageContent' : ActorMethod<[HomePageContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];