/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CourseCategory = IDL.Variant({
  'Engineering' : IDL.Null,
  'Pharmacy' : IDL.Null,
  'EntranceExam' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubmittedReview = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'name' : IDL.Opt(IDL.Text),
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ContactInfo = IDL.Record({
  'ownerName' : IDL.Text,
  'instagram' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'facebook' : IDL.Text,
  'phone' : IDL.Text,
  'branches' : IDL.Vec(IDL.Text),
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : CourseCategory,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const InternationalInquiry = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ReviewImage = IDL.Record({
  'id' : IDL.Text,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCourse' : IDL.Func(
      [IDL.Text, IDL.Text, CourseCategory, IDL.Text],
      [],
      [],
    ),
  'addOrUpdateGalleryImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'addReviewImage' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getAllSubmittedReviews' : IDL.Func(
      [],
      [IDL.Vec(SubmittedReview)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getInternationalInquiries' : IDL.Func(
      [],
      [IDL.Vec(InternationalInquiry)],
      ['query'],
    ),
  'getReviewImages' : IDL.Func([], [IDL.Vec(ReviewImage)], ['query']),
  'getSubmittedReviews' : IDL.Func([], [IDL.Vec(SubmittedReview)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeCourse' : IDL.Func([IDL.Text], [], []),
  'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
  'removeReviewImage' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInternationalInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateContactInfo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CourseCategory = IDL.Variant({
    'Engineering' : IDL.Null,
    'Pharmacy' : IDL.Null,
    'EntranceExam' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubmittedReview = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'name' : IDL.Opt(IDL.Text),
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ContactInfo = IDL.Record({
    'ownerName' : IDL.Text,
    'instagram' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'facebook' : IDL.Text,
    'phone' : IDL.Text,
    'branches' : IDL.Vec(IDL.Text),
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : CourseCategory,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const InternationalInquiry = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ReviewImage = IDL.Record({
    'id' : IDL.Text,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCourse' : IDL.Func(
        [IDL.Text, IDL.Text, CourseCategory, IDL.Text],
        [],
        [],
      ),
    'addOrUpdateGalleryImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'addReviewImage' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getAllSubmittedReviews' : IDL.Func(
        [],
        [IDL.Vec(SubmittedReview)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getInternationalInquiries' : IDL.Func(
        [],
        [IDL.Vec(InternationalInquiry)],
        ['query'],
      ),
    'getReviewImages' : IDL.Func([], [IDL.Vec(ReviewImage)], ['query']),
    'getSubmittedReviews' : IDL.Func([], [IDL.Vec(SubmittedReview)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeCourse' : IDL.Func([IDL.Text], [], []),
    'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
    'removeReviewImage' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInternationalInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateContactInfo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };